using System;
using System.Numerics;
using Content.Client.Resources;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;

namespace Content.Client._RMC14.Chemistry.TuringDispenser;

[GenerateTypedNameReferences]
public sealed partial class RMCTuringDispenserProgramRow : Control
{
    private const string VialIconPath = "/Textures/_RMC14/Objects/Chemistry/vials.rsi/vial.png";
    private const string VialFillIconPathFormat = "/Textures/_RMC14/Objects/Chemistry/vials.rsi/vial{0}.png";
    private const int MinFillLevel = 1;
    private const int MaxFillLevel = 6;

    private readonly IResourceCache _resourceCache;

    public RMCTuringDispenserProgramRow()
    {
        RobustXamlLoader.Load(this);

        _resourceCache = IoCManager.Resolve<IResourceCache>();

        VialIcon.Texture = _resourceCache.GetTexture(VialIconPath);
        VialIcon.SetSize = new Vector2(20, 20);

        VialFillIcon.SetSize = new Vector2(20, 20);
        SetFillFraction(1);
    }

    public void SetFillFraction(float fraction)
    {
        var level = Math.Clamp((int) Math.Ceiling(fraction * MaxFillLevel), MinFillLevel, MaxFillLevel);
        VialFillIcon.Texture = _resourceCache.GetTexture(string.Format(VialFillIconPathFormat, level));
    }
}
