using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Xenonids.Biomass;

[GenerateTypedNameReferences]
public sealed partial class RMCBiomassAnalyzerWindow : DefaultWindow
{
    public RMCBiomassAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
