using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Intel;

[GenerateTypedNameReferences]
public sealed partial class ViewIntelObjectivesWindow : DefaultWindow
{
    public ViewIntelObjectivesWindow()
    {
        RobustXamlLoader.Load(this);

        TabContainer.SetTabTitle(ObjectivesTab, Loc.GetString("rmc-ui-intel-objectives-tab"));
        TabContainer.SetTabTitle(ChemicalsTab, Loc.GetString("rmc-intel-chemicals-pending"));
    }
}
