using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Fishing;

[GenerateTypedNameReferences]
public sealed partial class RMCFishingMinigameWindow : DefaultWindow
{
    private readonly RMCFishingMinigameControl _control;

    public event Action<bool, int>? OnResult;

    public RMCFishingMinigameWindow()
    {
        RobustXamlLoader.Load(this);

        _control = new RMCFishingMinigameControl();
        _control.HorizontalExpand = true;
        _control.VerticalExpand = true;
        MinigameArea.AddChild(_control);
        _control.OnResult += (success, token) => OnResult?.Invoke(success, token);
    }

    public void StartMinigame(float difficulty, int token)
    {
        _control.Start(difficulty, token);
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (disposing)
            _control.Dispose();
    }
}
