using Content.Shared._RMC14.Chemistry.Generation;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Chemistry.Generation;

[GenerateTypedNameReferences]
public sealed partial class RMCChemSynthesizerWindow : DefaultWindow
{
    private RMCChemSynthesizerBui? _bui;

    public RMCChemSynthesizerWindow()
    {
        RobustXamlLoader.Load(this);

        Tier1Button.OnPressed += _ => _bui?.SetTier(1);
        Tier2Button.OnPressed += _ => _bui?.SetTier(2);
        Tier3Button.OnPressed += _ => _bui?.SetTier(3);
        SynthesizeButton.OnPressed += _ => _bui?.Synthesize();
    }

    public void SetBui(RMCChemSynthesizerBui bui)
    {
        _bui = bui;
    }

    public void UpdateState(RMCChemSynthesizerComponent comp, TimeSpan curTime)
    {
        Tier1Button.Pressed = comp.Tier == 1;
        Tier2Button.Pressed = comp.Tier == 2;
        Tier3Button.Pressed = comp.Tier == 3;

        var tierButtonsDisabled = comp.Processing;
        Tier1Button.Disabled = tierButtonsDisabled;
        Tier2Button.Disabled = tierButtonsDisabled;
        Tier3Button.Disabled = tierButtonsDisabled;

        SynthesizeButton.Disabled = comp.Processing;

        if (!comp.Processing)
        {
            StatusLabel.Text = "Ready";
            ProgressBar.Value = 0f;
            return;
        }

        var total = (float) comp.ProcessDuration.TotalSeconds;
        var remaining = (float) (comp.FinishAt - curTime).TotalSeconds;
        var ratio = total > 0f ? 1f - Math.Clamp(remaining / total, 0f, 1f) : 1f;
        StatusLabel.Text = "Synthesizing...";
        ProgressBar.Value = ratio;
    }
}
