using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Timing;

namespace Content.Client._RMC14.Chemistry.Generation;

[GenerateTypedNameReferences]
public sealed partial class RMCResearchComputerWindow : DefaultWindow
{
    [Dependency] private readonly IGameTiming _timing = default!;

    public TimeSpan CycleStart;
    public TimeSpan CycleEnd;

    public RMCResearchComputerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (CycleEnd <= CycleStart)
        {
            ContractCooldownBar.Value = 0;
            ContractCooldownLabel.Text = string.Empty;
            return;
        }

        var time = _timing.CurTime;
        var remaining = CycleEnd - time;
        if (remaining < TimeSpan.Zero)
            remaining = TimeSpan.Zero;

        ContractCooldownBar.MinValue = (float) CycleStart.TotalSeconds;
        ContractCooldownBar.MaxValue = (float) CycleEnd.TotalSeconds;
        ContractCooldownBar.Value = (float) time.TotalSeconds;
        ContractCooldownLabel.Text = $"Contracts Refresh in: {(int) remaining.TotalSeconds}";
    }
}
