using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Chemistry.Generation;

[GenerateTypedNameReferences]
public sealed partial class RMCSynthesisSimulatorWindow : DefaultWindow
{
    public RMCSynthesisSimulatorWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
