using Content.Client.UserInterface.Controls;
using Content.Shared._RMC14.Botany;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;

namespace Content.Client._RMC14.Botany;

[GenerateTypedNameReferences]
public sealed partial class GeneEditorWindow : FancyWindow
{
    private const string RadiationIcon = "/Textures/_RMC14/Interface/Icons/dark/radiation.svg.192dpi.png";
    private const string RadiationIconWhite = "/Textures/_RMC14/Interface/Icons/white/radiation.svg.192dpi.png";
    private const string EjectIcon = "/Textures/_RMC14/Interface/Icons/dark/eject.svg.192dpi.png";
    private const string EjectIconWhite = "/Textures/_RMC14/Interface/Icons/white/eject.svg.192dpi.png";

    private GeneEditorBui? _bui;

    public GeneEditorWindow()
    {
        RobustXamlLoader.Load(this);

        var resourceCache = IoCManager.Resolve<IResourceCache>();

        BotanyUiStyle.Header(DiscHeader);

        BotanyUiStyle.IconButton(resourceCache, ApplyButton, RadiationIcon, RadiationIconWhite, "Apply Genes");
        BotanyUiStyle.IconButton(resourceCache, EjectButton, EjectIcon, EjectIconWhite, "Eject All");

        ApplyButton.OnPressed += _ => _bui?.Apply();
        EjectButton.OnPressed += _ => _bui?.Eject();
    }

    public void SetBui(GeneEditorBui bui)
    {
        _bui = bui;
    }

    public void UpdateState(GeneEditorComponent comp)
    {
        if (comp.HasDisc)
            BotanyUiStyle.StatusRow(DiscStatusPanel, DiscStatusLabel, "[Disc loaded]", BotanyUiStyle.GreenColor);
        else
            BotanyUiStyle.StatusRow(DiscStatusPanel, DiscStatusLabel, "[No disc loaded]", BotanyUiStyle.RedColor);

        if (comp.HasDisc && comp.DiscSource != null)
        {
            DiscSourceLabel.Text = $"Source: {comp.DiscSource}";
            DiscSourceLabel.Visible = true;
        }
        else
        {
            DiscSourceLabel.Visible = false;
        }

        DiscGenesContainer.DisposeAllChildren();
        if (comp.HasDisc)
        {
            if (comp.DiscGeneLabels.Count == 0)
            {
                DiscGenesContainer.AddChild(new Label
                {
                    Text = "No genes stored on disc.",
                    StyleClasses = { "LabelSubText" },
                });
            }
            else
            {
                foreach (var label in comp.DiscGeneLabels)
                {
                    DiscGenesContainer.AddChild(new Label
                    {
                        Text = $"• {label}",
                    });
                }
            }
        }

        SeedSpriteView.Visible = comp.HasSeed && comp.SeedEntityNet.HasValue;
        if (comp.SeedEntityNet.HasValue)
            SeedSpriteView.SetEntity(comp.SeedEntityNet.Value);
        else
            SeedSpriteView.SetEntity((EntityUid?) null);

        SeedTraitsGrid.DisposeAllChildren();

        if (comp.HasSeed)
        {
            var seedText = comp.SeedName is { } seedName
                ? BotanyUiStyle.ShortSeedName(seedName)
                : "[Unknown seed]";
            BotanyUiStyle.StatusRow(SeedStatusPanel, SeedStatusLabel, seedText, BotanyUiStyle.GreenColor);
            SeedStatusLabel.ToolTip = comp.SeedName;

            var ratio = comp.MaxEditCount > 0
                ? comp.SeedEditCount / (float) comp.MaxEditCount
                : 0f;
            var color = ratio >= 1f ? BotanyUiStyle.RedColor : BotanyUiStyle.GreenColor;
            EditCountMetric.SetAccentColor(color);
            EditCountMetric.Update("Gene Edits", $"{comp.SeedEditCount}/{comp.MaxEditCount}", progress: ratio);

            BotanyUiStyle.AddStatRow(SeedTraitsGrid, "Endurance", $"{comp.SeedEndurance:0.#}");
            BotanyUiStyle.AddStatRow(SeedTraitsGrid, "Yield", $"{comp.SeedYield}");
            BotanyUiStyle.AddStatRow(SeedTraitsGrid, "Potency", $"{comp.SeedPotency:0.#}");
            BotanyUiStyle.AddStatRow(SeedTraitsGrid, "Lifespan", $"{comp.SeedLifespan:0.#}");
            BotanyUiStyle.AddStatRow(SeedTraitsGrid, "Maturation", $"{comp.SeedMaturation:0.#}");
            BotanyUiStyle.AddStatRow(SeedTraitsGrid, "Production", $"{comp.SeedProduction:0.#}");
            BotanyUiStyle.AddStatRow(SeedTraitsGrid, "Harvest", BotanyUiStyle.GetHarvestLabel(comp.SeedHarvestRepeat));
            BotanyUiStyle.AddStatRow(SeedTraitsGrid, "Seedless", comp.SeedSeedless ? "Yes" : "No");
            BotanyUiStyle.AddStatRow(SeedTraitsGrid, "Viable", comp.SeedViable ? "Yes" : "No");
        }
        else
        {
            BotanyUiStyle.StatusRow(SeedStatusPanel, SeedStatusLabel, "[No seed loaded]", BotanyUiStyle.RedColor);
            SeedStatusLabel.ToolTip = null;
            EditCountMetric.SetAccentColor(BotanyUiStyle.GreenColor);
            EditCountMetric.Update("Gene Edits", "—", progress: 0f);
        }
    }
}
