using Content.Shared._RMC14.Botany;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Botany;

[GenerateTypedNameReferences]
public sealed partial class GeneEditorWindow : DefaultWindow
{
    private GeneEditorBui? _bui;

    public GeneEditorWindow()
    {
        RobustXamlLoader.Load(this);

        ApplyButton.OnPressed += _ => _bui?.Apply();
        EjectButton.OnPressed += _ => _bui?.Eject();
    }

    public void SetBui(GeneEditorBui bui)
    {
        _bui = bui;
    }

    public void UpdateState(GeneEditorComponent comp)
    {
        DiscStatusLabel.Text = comp.HasDisc
            ? Loc.GetString("rmc-gene-editor-disc-present")
            : Loc.GetString("rmc-gene-editor-no-disc");

        if (comp.HasDisc && comp.DiscSource != null)
        {
            DiscSourceLabel.Text = Loc.GetString("rmc-gene-editor-disc-source", ("source", comp.DiscSource));
            DiscSourceLabel.Visible = true;
        }
        else
        {
            DiscSourceLabel.Visible = false;
        }

        DiscGenesContainer.DisposeAllChildren();
        if (comp.HasDisc)
        {
            if (comp.DiscGeneLabels.Count == 0)
            {
                DiscGenesContainer.AddChild(new Label
                {
                    Text = Loc.GetString("rmc-gene-editor-disc-no-genes"),
                    StyleClasses = { "LabelSubText" },
                });
            }
            else
            {
                foreach (var label in comp.DiscGeneLabels)
                {
                    DiscGenesContainer.AddChild(new Label
                    {
                        Text = Loc.GetString("rmc-gene-editor-gene-entry", ("gene", label)),
                    });
                }
            }
        }

        if (comp.HasSeed)
        {
            SeedStatusLabel.Text = comp.SeedName != null
                ? Loc.GetString("rmc-gene-editor-seed-present", ("name", comp.SeedName))
                : Loc.GetString("rmc-gene-editor-seed-present-unknown");

            var ratio = comp.MaxEditCount > 0
                ? comp.SeedEditCount / (float)comp.MaxEditCount
                : 0f;
            EditCountBar.Value = ratio;
            EditCountLabel.Text = Loc.GetString("rmc-gene-editor-edit-count-value",
                ("current", comp.SeedEditCount),
                ("max", comp.MaxEditCount));
        }
        else
        {
            SeedStatusLabel.Text = Loc.GetString("rmc-gene-editor-no-seed");
            EditCountBar.Value = 0f;
            EditCountLabel.Text = string.Empty;
        }

        ApplyButton.Disabled = !comp.HasDisc || !comp.HasSeed;
        EjectButton.Disabled = !comp.HasDisc && !comp.HasSeed;
    }
}
