using Content.Shared._RMC14.Botany;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;

namespace Content.Client._RMC14.Botany;

[GenerateTypedNameReferences]
public sealed partial class GeneEditorWindow : DefaultWindow
{
    private const string RadiationIcon = "/Textures/_RMC14/Interface/Icons/radiation.svg.192dpi.png";
    private const string RadiationIconWhite = "/Textures/_RMC14/Interface/Icons/radiation-white.svg.192dpi.png";
    private const string EjectIcon = "/Textures/_RMC14/Interface/Icons/eject.svg.192dpi.png";
    private const string EjectIconWhite = "/Textures/_RMC14/Interface/Icons/eject-white.svg.192dpi.png";

    private GeneEditorBui? _bui;

    public GeneEditorWindow()
    {
        RobustXamlLoader.Load(this);

        var resourceCache = IoCManager.Resolve<IResourceCache>();

        BotanyUiStyle.Header(DiscHeader);
        BotanyUiStyle.Header(SeedHeader);
        EditCountBar.ForegroundStyleBoxOverride = BotanyUiStyle.Flat(BotanyUiStyle.GreenColor);

        BotanyUiStyle.IconButton(resourceCache, ApplyButton, RadiationIcon, RadiationIconWhite, Loc.GetString("rmc-gene-editor-apply-button"));
        BotanyUiStyle.IconButton(resourceCache, EjectButton, EjectIcon, EjectIconWhite, Loc.GetString("rmc-gene-editor-eject-button"));

        ApplyButton.OnPressed += _ => _bui?.Apply();
        EjectButton.OnPressed += _ => _bui?.Eject();
    }

    public void SetBui(GeneEditorBui bui)
    {
        _bui = bui;
    }

    public void UpdateState(GeneEditorComponent comp)
    {
        if (comp.HasDisc)
            BotanyUiStyle.StatusRow(DiscStatusPanel, DiscStatusLabel, Loc.GetString("rmc-gene-editor-disc-present"), BotanyUiStyle.GreenColor);
        else
            BotanyUiStyle.StatusRow(DiscStatusPanel, DiscStatusLabel, Loc.GetString("rmc-gene-editor-no-disc"), BotanyUiStyle.RedColor);

        if (comp.HasDisc && comp.DiscSource != null)
        {
            DiscSourceLabel.Text = Loc.GetString("rmc-gene-editor-disc-source", ("source", comp.DiscSource));
            DiscSourceLabel.Visible = true;
        }
        else
        {
            DiscSourceLabel.Visible = false;
        }

        DiscGenesContainer.DisposeAllChildren();
        if (comp.HasDisc)
        {
            if (comp.DiscGeneLabels.Count == 0)
            {
                DiscGenesContainer.AddChild(new Label
                {
                    Text = Loc.GetString("rmc-gene-editor-disc-no-genes"),
                    StyleClasses = { "LabelSubText" },
                });
            }
            else
            {
                foreach (var label in comp.DiscGeneLabels)
                {
                    DiscGenesContainer.AddChild(new Label
                    {
                        Text = Loc.GetString("rmc-gene-editor-gene-entry", ("gene", label)),
                    });
                }
            }
        }

        SeedSpriteView.Visible = comp.HasSeed && comp.SeedEntityNet.HasValue;
        if (comp.SeedEntityNet.HasValue)
            SeedSpriteView.SetEntity(comp.SeedEntityNet.Value);
        else
            SeedSpriteView.SetEntity((EntityUid?) null);

        if (comp.HasSeed)
        {
            var seedText = comp.SeedName != null
                ? Loc.GetString("rmc-gene-editor-seed-present", ("name", comp.SeedName))
                : Loc.GetString("rmc-gene-editor-seed-present-unknown");
            BotanyUiStyle.StatusRow(SeedStatusPanel, SeedStatusLabel, seedText, BotanyUiStyle.GreenColor);

            var ratio = comp.MaxEditCount > 0
                ? comp.SeedEditCount / (float) comp.MaxEditCount
                : 0f;
            EditCountBar.Value = ratio;
            EditCountBar.ForegroundStyleBoxOverride = BotanyUiStyle.Flat(ratio >= 1f ? BotanyUiStyle.RedColor : BotanyUiStyle.GreenColor);
            EditCountLabel.Text = Loc.GetString("rmc-gene-editor-edit-count-value",
                ("current", comp.SeedEditCount),
                ("max", comp.MaxEditCount));
        }
        else
        {
            BotanyUiStyle.StatusRow(SeedStatusPanel, SeedStatusLabel, Loc.GetString("rmc-gene-editor-no-seed"), BotanyUiStyle.RedColor);
            EditCountBar.Value = 0f;
            EditCountBar.ForegroundStyleBoxOverride = BotanyUiStyle.Flat(BotanyUiStyle.GreenColor);
            EditCountLabel.Text = string.Empty;
        }

        BotanyUiStyle.SetButtonEnabled(ApplyButton, comp.HasDisc && comp.HasSeed);
        BotanyUiStyle.SetButtonEnabled(EjectButton, comp.HasDisc || comp.HasSeed);
    }
}
