using Content.Shared._RMC14.Botany;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Maths;

namespace Content.Client._RMC14.Botany;

[GenerateTypedNameReferences]
public sealed partial class LysisCentrifugeWindow : DefaultWindow
{
    private const string EjectIcon = "/Textures/_RMC14/Interface/Icons/eject.svg.192dpi.png";
    private const string EjectIconWhite = "/Textures/_RMC14/Interface/Icons/eject-white.svg.192dpi.png";
    private const string ProcessIcon = "/Textures/_RMC14/Interface/Icons/arrows-rotate.svg.192dpi.png";
    private const string ProcessIconWhite = "/Textures/_RMC14/Interface/Icons/arrows-rotate-white.svg.192dpi.png";
    private const string TrashIcon = "/Textures/_RMC14/Interface/Icons/trash.svg.192dpi.png";
    private const string TrashIconWhite = "/Textures/_RMC14/Interface/Icons/trash-white.svg.192dpi.png";
    private const string ExtractIcon = "/Textures/_RMC14/Interface/Icons/square-plus.svg.192dpi.png";
    private const string ExtractIconWhite = "/Textures/_RMC14/Interface/Icons/square-plus-white.svg.192dpi.png";

    private readonly IResourceCache _resourceCache;

    private LysisCentrifugeBui? _bui;

    public LysisCentrifugeWindow()
    {
        RobustXamlLoader.Load(this);

        _resourceCache = IoCManager.Resolve<IResourceCache>();

        BotanyUiStyle.Header(SeedHeader);
        BotanyUiStyle.Header(GenomeHeader);
        BotanyUiStyle.Header(DiscHeader);
        BotanyUiStyle.Header(GenesHeader);
        DegradationBar.ForegroundStyleBoxOverride = BotanyUiStyle.Flat(BotanyUiStyle.GreenColor);

        BotanyUiStyle.IconButton(_resourceCache, EjectSeedButton, EjectIcon, EjectIconWhite, "Eject Seed");
        BotanyUiStyle.IconButton(_resourceCache, ProcessSeedButton, ProcessIcon, ProcessIconWhite, "Process Genome");
        BotanyUiStyle.IconButton(_resourceCache, ClearBufferButton, TrashIcon, TrashIconWhite, "Clear Buffer");
        BotanyUiStyle.IconButton(_resourceCache, EjectDiscButton, EjectIcon, EjectIconWhite, "Eject Disc");

        ProcessSeedButton.OnPressed += _ => _bui?.ProcessSeed();
        EjectSeedButton.OnPressed += _ => _bui?.EjectSeed();
        ClearBufferButton.OnPressed += _ => _bui?.ClearBuffer();
        EjectDiscButton.OnPressed += _ => _bui?.EjectDisc();
    }

    public void SetBui(LysisCentrifugeBui bui)
    {
        _bui = bui;
    }

    public void UpdateState(LysisCentrifugeComponent comp)
    {
        SeedSpriteView.Visible = comp.HasSeed && comp.SeedEntityNet.HasValue;
        if (comp.SeedEntityNet.HasValue)
            SeedSpriteView.SetEntity(comp.SeedEntityNet.Value);
        else
            SeedSpriteView.SetEntity((EntityUid?) null);

        if (comp.HasSeed)
        {
            var seedText = comp.SeedPacketName ?? "[Seed inserted]";
            BotanyUiStyle.StatusRow(SeedStatusPanel, SeedStatusLabel, seedText, BotanyUiStyle.GreenColor);
        }
        else
        {
            BotanyUiStyle.StatusRow(SeedStatusPanel, SeedStatusLabel, "[No seed loaded]", BotanyUiStyle.RedColor);
        }

        BotanyUiStyle.SetButtonEnabled(EjectSeedButton, comp.HasSeed);
        BotanyUiStyle.SetButtonEnabled(ProcessSeedButton, comp.HasSeed && comp.GenomeName == null);

        var hasGenome = comp.GenomeName != null;

        if (hasGenome)
        {
            var ratio = comp.MaxDegradation > 0
                ? comp.Degradation / (float) comp.MaxDegradation
                : 0f;
            var color = ratio >= 0.75f ? BotanyUiStyle.RedColor : ratio >= 0.4f ? BotanyUiStyle.TanColor : BotanyUiStyle.GreenColor;

            BotanyUiStyle.StatusRow(GenomeStatusPanel, GenomeNameLabel, comp.GenomeName!, color);
            DegradationBar.Value = ratio;
            DegradationBar.ForegroundStyleBoxOverride = BotanyUiStyle.Flat(color);
            DegradationLabel.Text = $"{comp.Degradation}/{comp.MaxDegradation}";
            BotanyUiStyle.SetButtonEnabled(ClearBufferButton, true);
        }
        else
        {
            BotanyUiStyle.StatusRow(GenomeStatusPanel, GenomeNameLabel, "[No genome loaded]", BotanyUiStyle.RedColor);
            DegradationBar.Value = 0f;
            DegradationBar.ForegroundStyleBoxOverride = BotanyUiStyle.Flat(BotanyUiStyle.GreenColor);
            DegradationLabel.Text = string.Empty;
            BotanyUiStyle.SetButtonEnabled(ClearBufferButton, false);
        }

        if (comp.HasDisc)
            BotanyUiStyle.StatusRow(DiscStatusPanel, DiscStatusLabel, "[Disc inserted]", BotanyUiStyle.GreenColor);
        else
            BotanyUiStyle.StatusRow(DiscStatusPanel, DiscStatusLabel, "[No disc]", BotanyUiStyle.RedColor);

        BotanyUiStyle.SetButtonEnabled(EjectDiscButton, comp.HasDisc);

        GenesSection.Visible = hasGenome;

        GeneButtonsContainer.DisposeAllChildren();

        if (!hasGenome)
            return;

        foreach (var slot in comp.GeneSlots)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Thickness(0, 1),
            };

            var typeName = slot.GeneType.GetLabel();
            var typeDesc = slot.GeneType.GetDescription();
            var labelText = slot.AlreadyOnDisc
                ? $"{slot.ObfuscatedCode} - {typeName}: ✓"
                : $"{slot.ObfuscatedCode} - {typeName}:";

            var label = new Label
            {
                Text = labelText,
                ToolTip = typeDesc,
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center,
            };

            var geneType = slot.GeneType;
            var btnEnabled = comp.HasDisc && !slot.AlreadyOnDisc && !comp.DiscFull;
            string? btnTooltip = null;
            if (slot.AlreadyOnDisc)
                btnTooltip = "This gene sequence is already on the disc.";
            else if (comp.DiscFull)
                btnTooltip = "Disc already contains a gene sequence.";

            var btn = new Button { ToolTip = btnTooltip };
            BotanyUiStyle.IconButton(_resourceCache, btn, ExtractIcon, ExtractIconWhite, "Extract gene");
            BotanyUiStyle.SetButtonEnabled(btn, btnEnabled);
            btn.OnPressed += _ => _bui?.ExtractGene(geneType);

            row.AddChild(label);
            row.AddChild(btn);
            GeneButtonsContainer.AddChild(row);
        }
    }
}
