using Content.Shared._RMC14.Botany;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Botany;

[GenerateTypedNameReferences]
public sealed partial class LysisCentrifugeWindow : DefaultWindow
{
    private LysisCentrifugeBui? _bui;

    public LysisCentrifugeWindow()
    {
        RobustXamlLoader.Load(this);

        ProcessSeedButton.OnPressed += _ => _bui?.ProcessSeed();
        EjectSeedButton.OnPressed += _ => _bui?.EjectSeed();
        ClearBufferButton.OnPressed += _ => _bui?.ClearBuffer();
        EjectDiscButton.OnPressed += _ => _bui?.EjectDisc();
    }

    public void SetBui(LysisCentrifugeBui bui)
    {
        _bui = bui;
    }

    public void UpdateState(LysisCentrifugeComponent comp)
    {
        SeedStatusLabel.Text = comp.HasSeed
            ? comp.SeedPacketName ?? Loc.GetString("rmc-centrifuge-seed-loaded")
            : Loc.GetString("rmc-centrifuge-no-seed");
        EjectSeedButton.Disabled = !comp.HasSeed;
        ProcessSeedButton.Disabled = !comp.HasSeed || comp.GenomeName != null;

        if (comp.GenomeName != null)
        {
            GenomeNameLabel.Text = comp.GenomeName;
            DegradationBar.Value = comp.MaxDegradation > 0
                ? comp.Degradation / (float)comp.MaxDegradation
                : 0f;
            DegradationLabel.Text = Loc.GetString("rmc-centrifuge-degradation-value",
                ("current", comp.Degradation),
                ("max", comp.MaxDegradation));
            ClearBufferButton.Disabled = false;
        }
        else
        {
            GenomeNameLabel.Text = Loc.GetString("rmc-centrifuge-no-genome");
            DegradationBar.Value = 0f;
            DegradationLabel.Text = string.Empty;
            ClearBufferButton.Disabled = true;
        }

        DiscStatusLabel.Text = comp.HasDisc
            ? Loc.GetString("rmc-centrifuge-disc-loaded")
            : Loc.GetString("rmc-centrifuge-disc-empty");
        EjectDiscButton.Disabled = !comp.HasDisc;

        GeneButtonsContainer.DisposeAllChildren();

        var hasGenome = comp.GenomeName != null;
        foreach (var slot in comp.GeneSlots)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Thickness(0, 2),
            };

            var key = slot.GeneType.ToString().ToLower();
            var typeName = Loc.GetString($"rmc-gene-type-{key}");
            var typeDesc = Loc.GetString($"rmc-gene-type-{key}-desc");
            var labelText = slot.AlreadyOnDisc
                ? Loc.GetString("rmc-centrifuge-gene-label-copied", ("code", slot.ObfuscatedCode), ("type", typeName))
                : Loc.GetString("rmc-centrifuge-gene-label", ("code", slot.ObfuscatedCode), ("type", typeName));

            var label = new Label
            {
                Text = labelText,
                ToolTip = typeDesc,
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center,
            };

            var geneType = slot.GeneType;
            var btn = new Button
            {
                Text = Loc.GetString("rmc-centrifuge-extract-gene"),
                StyleClasses = { "ButtonSquare" },
                Disabled = !hasGenome || !comp.HasDisc || slot.AlreadyOnDisc,
                ToolTip = slot.AlreadyOnDisc ? Loc.GetString("rmc-centrifuge-gene-already-copied") : null,
            };
            btn.OnPressed += _ => _bui?.ExtractGene(geneType);

            row.AddChild(label);
            row.AddChild(btn);
            GeneButtonsContainer.AddChild(row);
        }
    }
}
