using Content.Client.UserInterface.Controls;
using Content.Shared._RMC14.Botany;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._RMC14.Botany;

[GenerateTypedNameReferences]
public sealed partial class RMCPlantAnalyzerWindow : FancyWindow
{
    public RMCPlantAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);

        BotanyUiStyle.Header(TraitsHeader);
        BotanyUiStyle.Header(NotesHeader);
        BotanyUiStyle.Header(VitalsHeader);
        BotanyUiStyle.Header(ConditionsHeader);
        BotanyUiStyle.Header(TrayHeader);
        BotanyUiStyle.Header(ChemicalsHeader);

        HealthMetric.SetAccentColor(BotanyUiStyle.MetricHealthColor);
        GrowthMetric.SetAccentColor(BotanyUiStyle.MetricGrowthColor);
        TemperatureMetric.SetAccentColor(BotanyUiStyle.MetricTemperatureColor);
        PressureMetric.SetAccentColor(BotanyUiStyle.MetricPressureColor);
        WaterMetric.SetAccentColor(BotanyUiStyle.MetricWaterColor);
        NutritionMetric.SetAccentColor(BotanyUiStyle.MetricNutrientsColor);
        PestMetric.SetAccentColor(BotanyUiStyle.MetricPestsColor);
        WeedMetric.SetAccentColor(BotanyUiStyle.MetricWeedsColor);
        ToxinMetric.SetAccentColor(BotanyUiStyle.MetricToxinsColor);
    }

    public void UpdateState(RMCPlantAnalyzerComponent comp)
    {
        TargetSpriteView.Visible = comp.DisplayEntity.HasValue;
        TargetSpriteView.SetEntity(comp.DisplayEntity);
        TargetNameLabel.Text = comp.PlantName;

        if (comp.TrayEmpty)
            BotanyUiStyle.StatusRow(TargetStatusPanel, TargetStatusLabel, "[Tray is empty]", BotanyUiStyle.RedColor);
        else
            BotanyUiStyle.StatusRow(TargetStatusPanel, TargetStatusLabel, "[Analyzed]", BotanyUiStyle.GreenColor);

        VitalsSection.Visible = comp.HasPlantData;
        TraitsSection.Visible = comp.HasPlantData || comp.IsProduce;
        ConditionsSection.Visible = comp.HasPlantData;
        TraySection.Visible = comp.IsTray && !comp.TrayEmpty;
        NotesSection.Visible = comp.Traits.Count > 0;
        ChemicalsSection.Visible = comp.Chemicals.Count > 0;

        MetricsColumn.Visible = VitalsSection.Visible || ConditionsSection.Visible || TraySection.Visible;

        if (comp.HasPlantData)
        {
            var healthRatio = comp.Endurance > 0f ? comp.Health / comp.Endurance : 1f;
            HealthMetric.Update("Health", $"{comp.Health:0.#} / {comp.Endurance:0.#}", progress: healthRatio);

            var growthRatio = comp.Maturation > 0f ? comp.Age / comp.Maturation : 1f;
            GrowthMetric.Update("Growth",
                comp.ReadyToHarvest ? "Ready to harvest" : $"{comp.Age} / {comp.Maturation:0.#} cycles",
                progress: comp.ReadyToHarvest ? 1f : growthRatio);

            TemperatureMetric.Update("Temperature", $"{comp.MinHeat:0.#}–{comp.MaxHeat:0.#} K");
            PressureMetric.Update("Pressure", $"{comp.MinPressure:0.#}–{comp.MaxPressure:0.#} kPa");

            TraitsGrid.DisposeAllChildren();
            BotanyUiStyle.AddStatRow(TraitsGrid, "Yield", $"{comp.Yield}");
            BotanyUiStyle.AddStatRow(TraitsGrid, "Potency", $"{comp.Potency:0.#}");
            BotanyUiStyle.AddStatRow(TraitsGrid, "Lifespan", $"{comp.Lifespan:0.#}");
            BotanyUiStyle.AddStatRow(TraitsGrid, "Production", $"{comp.Production:0.#}");
            BotanyUiStyle.AddStatRow(TraitsGrid, "Harvest", BotanyUiStyle.GetHarvestLabel(comp.HarvestRepeat));
            BotanyUiStyle.AddStatRow(TraitsGrid, "Seedless", comp.Seedless ? "Yes" : "No");
            BotanyUiStyle.AddStatRow(TraitsGrid, "Viable", comp.Viable ? "Yes" : "No");
        }
        else if (comp.IsProduce)
        {
            TraitsGrid.DisposeAllChildren();
            BotanyUiStyle.AddStatRow(TraitsGrid, "Potency", $"{comp.Potency:0.#}");
        }

        if (comp.IsTray && !comp.TrayEmpty)
        {
            WaterMetric.Update("Water", $"{comp.WaterLevel:0.#}", progress: comp.WaterLevel / 100f);
            NutritionMetric.Update("Nutrition", $"{comp.NutritionLevel:0.#}", progress: comp.NutritionLevel / 100f);
            PestMetric.Update("Pest", $"{comp.PestLevel:0.#}", progress: comp.PestLevel / 100f);
            WeedMetric.Update("Weed", $"{comp.WeedLevel:0.#}", progress: comp.WeedLevel / 100f);
            ToxinMetric.Update("Toxin", $"{comp.Toxins:0.#}", progress: comp.Toxins / 100f);
        }

        NotesContainer.DisposeAllChildren();
        foreach (var trait in comp.Traits)
        {
            var label = new RichTextLabel();
            label.SetMessage(trait);
            NotesContainer.AddChild(label);
        }

        ChemicalsContainer.DisposeAllChildren();
        var rowIndex = 0;
        foreach (var chem in comp.Chemicals)
        {
            ChemicalsContainer.AddChild(BuildChemicalRow(chem, rowIndex++));
        }
    }

    private static readonly Color RowColorA = Color.FromHex("#1B1B1E");
    private static readonly Color RowColorB = Color.FromHex("#202025");

    private static Control BuildChemicalRow(RMCPlantAnalyzerChemical chem, int rowIndex)
    {
        var marker = new PanelContainer
        {
            VerticalExpand = true,
            MinWidth = 4,
            Margin = new Thickness(0, 1, 6, 1),
            PanelOverride = new StyleBoxFlat { BackgroundColor = chem.Color },
        };

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(4, 2),
            Children =
            {
                marker,
                new Label { Text = chem.Name, HorizontalExpand = true },
                new Label
                {
                    Text = $"{chem.Min}–{chem.Max}u",
                    FontColorOverride = Color.FromHex("#9AA0AC"),
                },
            },
        };

        return new PanelContainer
        {
            PanelOverride = new StyleBoxFlat { BackgroundColor = rowIndex % 2 == 0 ? RowColorA : RowColorB },
            Children = { row },
        };
    }

}
